# Generated by Django 4.2.6 on 2023-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='названине')),
                ('anons', models.CharField(max_length=250, verbose_name='анонс')),
                ('text', models.TextField(verbose_name='статья')),
                ('time', models.DateTimeField(verbose_name='время публикации')),
            ],
        ),
    ]
