# Generated by Django 4.2.6 on 2023-10-27 10:32

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articales',
            name='picture',
            field=models.FileField(null=True, upload_to=news.models.Articales.file_path),
        ),
        migrations.AlterField(
            model_name='articales',
            name='title',
            field=models.CharField(max_length=50, verbose_name='название'),
        ),
    ]
